#!/usr/bin/perl

#
# tac - program to reverse the order and contents of a set of input files
#       usage: tac [filename ...]
#              filename: name of a file to reverse
#

use strict;
use warnings;

print((scalar reverse <>) . "\n");

